version: "2"
services:
   demo:
     image: infracloudio/csvserver
     ports: 
       - 9393:9300
     expose:
       - "9300"
     volumes:
       - type: bind
         source: "./inputFile"
         target: "/csvserver/inputdata"
     env_file:
       - csvserver.env
   prometheus:
     image: prom/prometheus:v2.22.0
     ports: 
       - 9090:9090
     volumes:
       - type: bind
         source: "./prometheus.yml"
         target: "/etc/prometheus/prometheus.yml"
     depends_on:
       - demo  
