global:
  scrape_interval: 10s
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'csvserver_endpoint'
    metrics_path: /metrics
    static_configs:
      - targets: ['solution-demo-1:9300']
